packages:
  - "apps/*"
  - "services/*"
  - "libs/*"

# Re-enable strict mode for better dependency management
strictPeerDependencies: true

# Document known safe exceptions (NestJS 11 compatibility)
pnpm:
  peerDependencyRules:
    ignoreMissing:
      - "@nestjs/common"
      - "@nestjs/core"
